version: '3'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties:ro
      - ./elasticsearch/dictionary:/usr/share/elasticsearch/config/analysis:ro
      - /app/elasticsearch/data:/usr/share/elasticsearch/data
      - elasticsearch-log:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx16g -Xms16g"
      ELASTIC_PASSWORD: xkdlem0!
      discovery.type: single-node
    networks:
      - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    hostname: filebeat
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/filebeat:/var/log/filebeat
      - elasticsearch-log:/usr/share/elasticsearch/logs:ro
    command: filebeat -e -strict.perms=false
    restart: always
    environment:
      - "ES_HOSTS=http://elasticsearch:9200"
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - elk

volumes:
  elasticsearch-log:

networks:
  elk:
    driver: bridge
